#Add values for any properties you wish to change when updating connections.
#Delete any lines that you don't want to update values.
#FlexDeploy properties or plain text are allowed.
See the documentation at https://wiki.flexagon.com for more information.


######################## SIMPLE_PROJECT:CONNECTIONTEST ########################

#connectionType
SIMPLE_PROJECT:CONNECTIONTEST.connection.Connection Type=restUrl

#tlsVersion
SIMPLE_PROJECT:CONNECTIONTEST.connection.TLS Version=

#connectionUrl
SIMPLE_PROJECT:CONNECTIONTEST.connection.Connection URL=http://www.gmail.com

#enableTwoWaySSL
SIMPLE_PROJECT:CONNECTIONTEST.connection.Enable two way SSL for outbound connections (Optional)=

#sslCertificateAlias
SIMPLE_PROJECT:CONNECTIONTEST.connection.Identity keystore alias name (Optional)=
SIMPLE_PROJECT:CONNECTIONTEST.agentDefinition=

